function [  ] = about( )
%ABOUT Summary of this function goes here
%   Detailed explanation goes here
%load 'Title'
h1 = figure('Units','normalized', ...
    'Color',[0 0.56 .75], ...
    'CreateFcn',' ', ...% Hyperspec4h create
    'Name','双向反射数据处理软件V1.0', ...
    'NumberTitle','off', ...
    'PaperOrientation','landscape', ...
    'PaperType','a4letter', ...
    'Position',[0.4 0.4 0.3 0.3], ...
    'menubar','none',...
    'Tag','Fig1');
% PROGRAM AUTHOR
h2 = uicontrol('Parent',h1, ...
    'Units','normalized', ...
    'BackgroundColor',[0 0.56 .75], ...
    'FontSize',12, ...
    'FontWeight','bold',...
    'ForegroundColor',[1 1 0], ...
    'ListboxTop',0, ...
    'HandleVisibility','off',...
    'Position',[0.6 0.1 0.2 0.24], ...
    'String','开发者：浙江大学', ...
    'Style','text', ...
    'Tag','StaticText10');
% MAIN TITLE
h2 = uicontrol('Parent',h1, ...
    'Units','normalized', ...
    'BackgroundColor',[0 0.56 .75], ...
    'FontSize',24, ...
    'FontWeight','bold',...
    'ForegroundColor',[1 1 0], ...
    'HandleVisibility','off',...
    'HorizontalAlignment','center',...
    'Position',[0.25 0.887 0.442 0.08], ...
    'String','关于...', ...
    'Style','text', ...
    'Tag','StaticText1');
h2 = uicontrol('Parent',h1, ...
    'Units','normalized', ...
    'BackgroundColor',[0 0.56 .75], ...
    'FontSize',16, ...
    'FontWeight','bold',...
    'ForegroundColor',[1 1 0], ...
    'ListboxTop',0, ...
    'Position',[0.113 0.67 0.716 0.176], ...
    'String','软件功能介绍', ...
    'Style','text', ...
    'Tag','StaticText2');
% LOADING IMAGES
h2 = uicontrol('Parent',h1, ...
    'Units','normalized', ...
    'BackgroundColor',[0 0.56 0.75], ...
    'FontSize',14, ...
    'FontWeight','bold',...
    'ForegroundColor',[1 1 0], ...
    'ListboxTop',0, ...
    'Position',[0.12 0.518 0.69 0.2], ...
    'String','双向反射数据软件是基于Matlab开发的数据处理软件，可用于漫反射板数据处理、叶片数据处理、以及绘制BRDF图像.', ...
    'Style','text', ...
    'Tag','StaticText3');
% close;
end

